build-image:
  stage: build
  tags:
    - build-docker
  image: docker:latest
  script:
    - docker context create buildx-build
    - docker buildx create --use buildx-build
    - >-
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
      $CI_REGISTRY
    - >-
      docker buildx build --no-cache --push --platform
      linux/amd64,linux/arm64/v8 -t $CI_REGISTRY_IMAGE:$WORDPRESS_VERSION-php$PHP_VERSION
      .
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  only:
    - main
  parallel:
    matrix:
      - PHP_VERSION: '8.1'
        WORDPRESS_VERSION:
          - '5.9.10'
          - '6.0.9'
          - '6.1.7'
          - '6.2.6'
          - '6.3.5'
          - '6.4.5'
          - '6.5.5'
          - '6.6.2'
          - '6.7.2'
      - PHP_VERSION: '8.2'
        WORDPRESS_VERSION:
          - '6.1.7'
          - '6.2.6'
          - '6.3.5'
          - '6.4.5'
          - '6.5.5'
          - '6.6.2'
          - '6.7.2'
      - PHP_VERSION: '8.3'
        WORDPRESS_VERSION:
          - '6.4.5'
          - '6.5.5'
          - '6.6.2'
          - '6.7.2'
      - PHP_VERSION: '8.4'
        WORDPRESS_VERSION:
          - '6.7.2'
